# Generated by Django 5.2.7 on 2025-11-07 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Час створення')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Час оновлення')),
                ('summary', models.CharField(blank=True, help_text='Короткий опис діалогу (перше повідомлення або заголовок)', max_length=200, null=True, verbose_name='Короткий опис')),
                ('is_active', models.BooleanField(default=True, help_text='Чи є сесія активною', verbose_name='Активна сесія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'AI Сесія',
                'verbose_name_plural': 'AI Сесії',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'Користувач'), ('assistant', 'ШІ-асистент')], db_index=True, max_length=20, verbose_name='Відправник')),
                ('message_text', models.TextField(verbose_name='Текст повідомлення')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Контекст для RAG: попередні повідомлення, embeddings, тощо', null=True, verbose_name='Контекст RAG')),
                ('sources', models.JSONField(blank=True, default=list, help_text='Джерела інформації використані для відповіді (документи, статті)', null=True, verbose_name='Джерела')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Додаткова інформація: модель, версія API, параметри запросу', null=True, verbose_name='Метадані')),
                ('status', models.CharField(choices=[('pending', 'Обробляється'), ('completed', 'Завершено'), ('error', 'Помилка')], db_index=True, default='completed', max_length=20, verbose_name='Статус обробки')),
                ('token_count', models.IntegerField(blank=True, help_text='Кількість токенів в повідомленні', null=True, verbose_name='Кількість токенів')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Час обробки запиту мікросервісом в мілісекундах', null=True, verbose_name='Час відповіді (мс)')),
                ('error_message', models.TextField(blank=True, help_text='Повідомлення про помилку якщо статус = error', null=True, verbose_name='Повідомлення про помилку')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Час створення')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatAI.aisession', verbose_name='Сесія')),
            ],
            options={
                'verbose_name': 'AI Повідомлення',
                'verbose_name_plural': 'AI Повідомлення',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['user', '-updated_at'], name='chatAI_aise_user_id_2a93d6_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['user', '-created_at'], name='chatAI_aise_user_id_52c3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['session', 'created_at'], name='chatAI_aime_session_7aadd8_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['sender', 'created_at'], name='chatAI_aime_sender_7d02ab_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['status'], name='chatAI_aime_status_433561_idx'),
        ),
    ]
