# Generated by Django 5.2.7 on 2025-11-07 15:15

import card.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Порція їжі',
                'verbose_name_plural': 'Порції їжі',
            },
        ),
        migrations.CreateModel(
            name='TypeOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тип активності',
                'verbose_name_plural': 'Типи активності',
            },
        ),
        migrations.CreateModel(
            name='FoodMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Сніданок', 'Сніданок'), ('Перекус', 'Перекус'), ('Обід', 'Обід'), ('Другий перекус', 'Другий перекус'), ('Вечеря', 'Вечеря')], default='Сніданок', max_length=50)),
                ('insuline_dose_before', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insuline_dose_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_of_measurement', models.DateField(default=django.utils.timezone.localdate)),
                ('time_of_eating', models.TimeField(default=card.models.current_local_time)),
                ('bread_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.patient')),
            ],
            options={
                'verbose_name': 'Замір їжі',
                'verbose_name_plural': 'Заміри їжі',
                'ordering': ['-date_of_measurement', '-time_of_eating'],
            },
        ),
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.fooditem')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='card.foodmeasurement')),
            ],
            options={
                'verbose_name': 'Порція',
                'verbose_name_plural': 'Порції',
            },
        ),
        migrations.AddField(
            model_name='foodmeasurement',
            name='food_items',
            field=models.ManyToManyField(related_name='food_measurements', through='card.FoodPortion', to='card.fooditem'),
        ),
        migrations.CreateModel(
            name='GlucoseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(35)])),
                ('glucose_measurement_category', models.CharField(blank=True, choices=[('Натщесердце', 'Натщесердце'), ('До сніданку', 'До сніданку'), ('Після сніданку', 'Після сніданку'), ('Перед перекусом', 'Перед перекусом'), ('Після перекусу', 'Після перекусу'), ('До обіду', 'До обіду'), ('Після обіду', 'Після обіду'), ('До вечері', 'До вечері'), ('Після вечері', 'Після вечері'), ('Перед сном', 'Перед сном'), ('Інше', 'Інше')], max_length=50, null=True)),
                ('date_of_measurement', models.DateField(default=django.utils.timezone.localdate)),
                ('time_of_measurement', models.TimeField(default=card.models.current_local_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.patient')),
            ],
            options={
                'verbose_name': 'Замір глюкози',
                'verbose_name_plural': 'Заміри глюкози',
                'ordering': ['-date_of_measurement', '-time_of_measurement'],
            },
        ),
        migrations.CreateModel(
            name='InsulineDoseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Натщесердце', 'Натщесердце'), ('До сніданку', 'До сніданку'), ('Після сніданку', 'Після сніданку'), ('Перед перекусом', 'Перед перекусом'), ('Після перекусу', 'Після перекусу'), ('До обіду', 'До обіду'), ('Після обіду', 'Після обіду'), ('До вечері', 'До вечері'), ('Після вечері', 'Після вечері'), ('Перед сном', 'Перед сном'), ('Інше', 'Інше')], max_length=50)),
                ('insuline_dose', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_of_measurement', models.DateField(default=django.utils.timezone.localdate)),
                ('time', models.TimeField(default=card.models.current_local_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.patient')),
            ],
            options={
                'verbose_name': 'Замір інсуліну',
                'verbose_name_plural': 'Заміри інсуліну',
                'ordering': ['-date_of_measurement', '-time'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalActivityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_approaches', models.IntegerField(blank=True, null=True)),
                ('date_of_measurement', models.DateField(default=django.utils.timezone.localdate)),
                ('time_of_activity', models.TimeField(default=card.models.current_local_time)),
                ('commentary', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.patient')),
                ('type_of_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.typeofactivity')),
            ],
            options={
                'verbose_name': 'Замір фізичної активності',
                'verbose_name_plural': 'Заміри фізичної активності',
                'ordering': ['-date_of_measurement', '-time_of_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='foodmeasurement',
            index=models.Index(fields=['patient', 'date_of_measurement'], name='card_foodme_patient_86e430_idx'),
        ),
        migrations.AddIndex(
            model_name='glucosemeasurement',
            index=models.Index(fields=['patient', 'date_of_measurement'], name='card_glucos_patient_3be7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='insulinedosemeasurement',
            index=models.Index(fields=['patient', 'date_of_measurement'], name='card_insuli_patient_975e71_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalactivitymeasurement',
            index=models.Index(fields=['patient', 'date_of_measurement'], name='card_physic_patient_d8396f_idx'),
        ),
    ]
