# Generated by Django 5.2.7 on 2025-11-08 17:12

import card.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthropometricMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('measurement_time', models.TimeField(default=card.models.current_local_time)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('waist_circumference', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('hip_circumference', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anthropometric_measurements', to='user_auth.patient')),
            ],
            options={
                'verbose_name': 'Антропометричний замір',
                'verbose_name_plural': 'Антропометричні заміри',
                'ordering': ['-measurement_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'measurement_date'], name='card_anthro_patient_9ddc18_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlycemicProfileMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('measurement_time', models.TimeField(default=card.models.current_local_time)),
                ('average_glucose', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('hba1c', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('hypoglycemic_events', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hyperglycemic_events', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glycemic_profile_measurements', to='user_auth.patient')),
            ],
            options={
                'verbose_name': 'Замір глюкозного профілю',
                'verbose_name_plural': 'Заміри глюкозного профілю',
                'ordering': ['-measurement_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'measurement_date'], name='card_glycem_patient_6c71be_idx')],
            },
        ),
    ]
