# Generated by Django 5.2.7 on 2025-11-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=500, unique=True)),
                ('article_short_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('article_author', models.CharField(blank=True, max_length=255, null=True)),
                ('article_description', models.CharField(blank=True, max_length=500, null=True)),
                ('article_img', models.ImageField(upload_to='articles-img/')),
                ('article_text', models.TextField(max_length=6000)),
                ('date_of_creation', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_of_creation'],
            },
        ),
    ]
